name: PolarWarps
main: me.blueslime.polarwarps.PolarWarps
api-version: 1.13
version: 1.0.1-SNAPSHOT
softdepend:
  - PlaceholderAPI
commands:
  warp:
    aliases: []
  warps:
    aliases: []
  setwarp:
    aliases: []
  delwarp:
    aliases: []
  polarwarps:
    aliases: [pw]

permissions:
  polarwarps.warp.set:
    default: op
  polarwarps.warp.delete:
    default: op
  polarwarps.reload:
    default: op