name: PolarWarps
main: me.blueslime.polarwarps.PolarWarps
api-version: 1.13
version: 1.0.1-SNAPSHOT
commands:
  warp:
    aliases: []
  setwarp:
    aliases: []
  delwarp:
    aliases: []
  polarwarps:
    aliases: [pw]

permissions:
  polarwarps.help:
    default: true
  polarwarps.warp:
    default: true
  polarwarps.setwarp:
    default: op
  polarwarps.delwarp:
    default: op
  polarwarps.reload:
    default: op