#  ┏━━━┳━━━┳┓╋╋┏━━━┳━━━┓┏┓┏┓┏┳━━━┳━━━┳━━━┳━━━┓
#  ┃┏━┓┃┏━┓┃┃╋╋┃┏━┓┃┏━┓┃┃┃┃┃┃┃┏━┓┃┏━┓┃┏━┓┃┏━┓┃
#  ┃┗━┛┃┃╋┃┃┃╋╋┃┃╋┃┃┗━┛┃┃┃┃┃┃┃┃╋┃┃┗━┛┃┗━┛┃┗━━┓
#  ┃┏━━┫┃╋┃┃┃╋┏┫┗━┛┃┏┓┏┛┃┗┛┗┛┃┗━┛┃┏┓┏┫┏━━┻━━┓┃
#  ┃┃╋╋┃┗━┛┃┗━┛┃┏━┓┃┃┃┗┓┗┓┏┓┏┫┏━┓┃┃┃┗┫┃╋╋┃┗━┛┃
#  ┗┛╋╋┗━━━┻━━━┻┛╋┗┻┛┗━┛╋┗┛┗┛┗┛╋┗┻┛┗━┻┛╋╋┗━━━┛
#
# Created by JustJustin
# Version: 1.0.3-SNAPSHOT
#
# Change the default welcome message on /setwarp
default-welcome-message:
  - "&aWelcome to this warp"
  - "&eStore.server.net"

settings:
  # Toggle the /warps command, disabled by default
  # Changes are only applied with server restart
  enable-warps-command: false
  # Options: ACTION_BAR (ACTIONBAR, AB, ACTION, 3) TITLE (TT, 2) SUBTITLE (SUB_TITLE, SUB-TITLE, SUB ,1) MESSAGE (TEXT, MSG, 0)
  time-left-type: ACTION_BAR
  # Toggle component usage (Only if your server is 1.16+ to allow Gradient and Hex Support)
  use-components: false